ComputerAccessories/ViewModels/AttributeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerAccessories.ViewModels
{
    public class AttributeViewModel
    {
        public int Id { get; set; }
        public string AttributeName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}

ComputerAccessories/ViewModels/BrandViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerAccessories.ViewModels
{
    public class BrandViewModel
    {
    }
}

ComputerAccessories/ViewModels/CategoryViewModel.cs
using ComputerAccessories.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ComputerAccessories.ViewModels
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public int? ParentCateId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ParentName { get; set; }
        public List<TblCategory> listParent { get; set; }
    }
}

ComputerAccessories/Areas/Admin/Controllers/MainServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ComputerAccessories.Models;
using ComputerAccessories.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting.Internal;

namespace ComputerAccessories.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MainServiceController : Controller
    {

        private HostingEnvironment hostingEnviroment;

        private readonly ComputerAccessoriesContext _db;
        [BindProperty]
        public CategoryViewModel CategoryVM { get; set; }
        [BindProperty]
        public AttributeViewModel AttributeVM { get; set; }
        public MainServiceController(ComputerAccessoriesContext db)
        {
            _db = db;
            CategoryVM = new CategoryViewModel
            {
                listParent = _db.TblCategory.ToList()
            };
            AttributeVM = new AttributeViewModel();

            hostingEnviroment = new HostingEnvironment();
        }
        #region Front
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Attributes(string categoryId = null, string fromTime = null, string toTime=null)
        {
            ViewBag.controller = "Attributes";
            var listCategory = _db.TblCategory.ToList();
            ViewBag.lstCategory = listCategory;
            if (string.IsNullOrEmpty(categoryId))
            {
                if (string.IsNullOrEmpty(fromTime) || string.IsNullOrEmpty(toTime))
                {
                    var lstAttributes = _db.TblAttribute.Select(x => new AttributeViewModel
                    {
                        Id = x.Id,
                        CategoryId = x.CategoryId,
                        AttributeName = x.AttributeName,
                        CreatedDate = x.CreatedDate,
                        ModifiedDate = x.ModifiedDate,
                        CategoryName = x.Category.CategoryName
                    }).ToList();
                    return View(lstAttributes);
                }
                else
                {
                    DateTime from = DateTime.Parse(fromTime);
                    DateTime to = DateTime.Parse(toTime + " 23:59:59");
                    var lstAttributes = _db.TblAttribute.Where(x=>x.CreatedDate>=from && x.CreatedDate<=to).Select(x => new AttributeViewModel
                    {
                        Id = x.Id,
                        CategoryId = x.CategoryId,
                        AttributeName = x.AttributeName,
                        CreatedDate = x.CreatedDate,
                        ModifiedDate = x.ModifiedDate,
                        CategoryName = x.Category.CategoryName
                    }).ToList();
                    return View(lstAttributes);
                }
            }
            else
            {
                var categoryid = Convert.ToInt32(categoryId);
                if (string.IsNullOrEmpty(fromTime) || string.IsNullOrEmpty(toTime))
                {
                    var lstAttributes = _db.TblAttribute.Where(x=>x.CategoryId == categoryid).Select(x => new AttributeViewModel
                    {
                        Id = x.Id,
                        CategoryId = x.CategoryId,
                        AttributeName = x.AttributeName,
                        CreatedDate = x.CreatedDate,
                        ModifiedDate = x.ModifiedDate,
                        CategoryName = x.Category.CategoryName
                    }).ToList();
                    return View(lstAttributes);
                }
                else
                {
                    DateTime from = DateTime.Parse(fromTime);
                    DateTime to = DateTime.Parse(toTime + "23:59:59");
                    var lstAttributes = _db.TblAttribute.Where(x => x.CreatedDate >= from && x.CreatedDate <= to&&x.CategoryId==categoryid).Select(x => new AttributeViewModel
                    {
                        Id = x.Id,
                        CategoryId = x.CategoryId,
                        AttributeName = x.AttributeName,
                        CreatedDate = x.CreatedDate,
                        ModifiedDate = x.ModifiedDate,
                        CategoryName = x.Category.CategoryName
                    }).ToList();
                    return View(lstAttributes);

                }
            }
            return View();

        }
        #region Category
        
        public PartialViewResult _GetCategory()
        {
            var listCategory = _db.TblCategory.ToList();
            ViewBag.lstCategory = listCategory;
            return PartialView("~/Views/Admin/_GetCategory.cshtml", listCategory);
        }
        [HttpPost]
        public async Task<IActionResult> CreateNewCategory(CategoryViewModel categoryView)
        {
            _db.TblCategory.Add(new TblCategory
            {
                CategoryName = categoryView.CategoryName,
                CreatedDate = DateTime.Now,
                ParentCateId = categoryView.ParentCateId,
            });
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Category));
        }

        

        public IActionResult Category()
        {
            var listCategory = _db.TblCategory.Where(x=>x.Id !=2).ToList();
            List<CategoryViewModel> lstCategory = new List<CategoryViewModel>();

            foreach (var item in listCategory)
            {
                if(item.ParentCateId != null)
                {
                    var parentName = _db.TblCategory.Where(x => x.Id == item.ParentCateId).Select(x => x.CategoryName).FirstOrDefault();

                    CategoryViewModel category = new CategoryViewModel()
                    {
                        CategoryName = item.CategoryName,
                        CreatedDate = item.CreatedDate,
                        ModifiedDate = item.ModifiedDate,
                        ParentName = parentName,
                        Id = item.Id
                    };
                    lstCategory.Add(category);
                }
                else
                {
                    CategoryViewModel category = new CategoryViewModel()
                    {
                        CategoryName = item.CategoryName,
                        CreatedDate = item.CreatedDate,
                        ModifiedDate = item.ModifiedDate,
                        Id = item.Id
                    };
                    lstCategory.Add(category);
                }
                
            }
            ViewBag.controller = "Category";
            return View(lstCategory);
        }
        [Route("/[controller]/GetCategory")]
        [HttpGet]
        public JsonResult GetCategory()
        {
            return Json(_db.TblCategory.Where(x=>x.Id !=2).ToList());
        }

        public IActionResult CreateNewCategory()
        {

            return View(CategoryVM);
        }

        public IActionResult CreateNewAttribute()
        {
            var categories = _db.TblCategory.ToList();
            ViewBag.lstCategory = categories;
            return View(AttributeVM);
        }

        public IActionResult EditBrand(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brandFromDb = _db.TblBrand.Where(x => x.Id == id).FirstOrDefault();
            return View(brandFromDb);
        }

        public IActionResult EditCategory(int? id)
        {
            if(id == null)
            {
                    return NotFound();
            }
            var categoryFromDb = _db.TblCategory.Where(x => x.Id == id).FirstOrDefault();
            if(categoryFromDb == null)
            {
                return NotFound();
            }
            CategoryVM.CategoryName = categoryFromDb.CategoryName;
            CategoryVM.ParentCateId = categoryFromDb.ParentCateId;
            CategoryVM.CreatedDate = categoryFromDb.CreatedDate;
            CategoryVM.ModifiedDate = categoryFromDb.ModifiedDate;
            CategoryVM.Id = categoryFromDb.Id;
 
            return View(CategoryVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory(TblCategory category)
        {
            if (category == null)
            {
                return NotFound();
            }
            var categoryFromDb = _db.TblCategory.Where(x => x.Id == category.Id).FirstOrDefault();
            categoryFromDb.CategoryName = category.CategoryName;
            categoryFromDb.ModifiedDate = DateTime.Now;
            categoryFromDb.ParentCateId = category.ParentCateId;
            var result = await _db.SaveChangesAsync();
            if (result > 0)
            {
                return RedirectToAction(nameof(Category));
            }
            return null;
        }
        
        #endregion
        #region Attribute
        [HttpGet]
        public IActionResult Attributes(string categoryId = null, string fromTime = null, string toTime = null)
        {
            ViewBag.controller = "Attributes";
            var listCategory = _db.TblCategory.ToList();
            ViewBag.lstCategory = listCategory;
            if (string.IsNullOrEmpty(categoryId))
            {
                if (string.IsNullOrEmpty(fromTime) || string.IsNullOrEmpty(toTime))
                {
                    var lstAttributes = _db.TblAttribute.Select(x => new AttributeViewModel
                    {
                        Id = x.Id,
                        CategoryId = x.CategoryId,
                        AttributeName = x.AttributeName,
                        CreatedDate = x.CreatedDate,
                        ModifiedDate = x.ModifiedDate,
                        CategoryName = x.Category.CategoryName
                    }).ToList();
                    return View(lstAttributes);
                }

ComputerAccessories/Areas/Admin/Views/MainService/AccountManager.cshtml
@model List<ComputerAccessories.ViewModels.AccountViewModel>
@{
    ViewData["VTitle"] = "AccountManager";
    Layout = "~/Views/Admin/_Layout.cshtml";
}


<div class="page-header">
    <div class="row">
        <div class="col-lg-10">
            <h3>Danh sách tài khoản</h3>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-default" asp-area="Admin" asp-controller="MainService" asp-action="CreateNewUser"><span><i class="fa fa-plus"></i></span> Thêm brand mới</a>
        </div>
    </div>
</div>
<br />

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Hover Data Table</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead style="color:darkcyan">
                        <tr>
                            <th>Mã</th>
                            <th>Họ tên</th>
                            <th>Email</th>
                            <th>Ngày tạo </th>
                            <th>Vai trò</th>
                            <th>Trạng thái</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>
                                    <a href="#">@item.Id</a>
                                </th>
                                <th>@item.DisplayName</th>
                                <th>@item.Email</th>
                                <th>@item.CreatedDate</th>
                                <th>@item.RoleName</th>
                                <th>@item.IsActivated</th>
                                <th>
                                    <partial name="~/Views/Shared/_TableButtonPartial.cshtml" model="@item.Id" />
                                </th>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                            <tr>
                                <th>Rendering engine</th>
                                <th>Browser</th>
                                <th>Platform(s)</th>
                                <th>Engine version</th>
                                <th>CSS grade</th>
                                <th></th>
                            </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

</div>


ComputerAccessories/Areas/Admin/Views/MainService/Attributes.cshtml
@using ComputerAccessories.Extensions
@model List<ComputerAccessories.ViewModels.AttributeViewModel>
@{
    ViewData["Title"] = "Attributes";
    Layout = "~/Views/Admin/_Layout.cshtml";
    IEnumerable<TblCategory> categories = new List<TblCategory>();
    categories = ViewBag.lstCategory;
}

<br />
<div class="page-header">
    <div class="row">

        <div class="col-lg-10">
            <i class="fab fa-git-alt"></i>
            <h3>Thuộc tính sản phẩm</h3>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-default" asp-area="Admin" asp-controller="MainService" asp-action="CreateNewAttribute"><span><i class="fa fa-plus"></i></span> Thêm sản danh mục</a>
        </div>
        <div class="col-lg-1">
        </div>
    </div>
</div>
<section class="content">

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Lọc</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Danh mục</label>
                            <select class="form-control select2 select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true" asp-items="@categories.ToSelectListItem("CategoryName",categories.FirstOrDefault().Id)" id="CategoryId"></select>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Từ ngày</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" @*asp-for="CreatedDate"*@ class="form-control pull-right" id="datepicker1">
                            </div>
                        </div>
                        <!-- /.form-group -->
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Đến ngày</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" @*asp-for="CreatedDate"*@ class="form-control pull-right" id="datepicker2">
                            </div>
                        </div>
                        <!-- /.form-group -->
                        <!-- /.form-group -->
                    </div>

                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-lg-4">
                        <a class="btn btn-success" onclick="Filter()" >Lọc</a>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>

    
   
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead style="color:darkcyan">
                            <tr>
                                <th>Mã</th>
                                <th>Tên thuộc tính</th>
                                <th>Danh mục</th>
                                <th>Ngày tạo </th>
                                <th>Ngày chỉnh sửa</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>@item.Id</th>
                                    <th>@item.AttributeName</th>
                                    @if (item.CategoryName == null)
                                    {
                                        <th>Trống</th>
                                    }
                                    else
                                    {
                                        <th>@item.CategoryName</th>

                                    }
                                    <th>@item.CreatedDate</th>
                                    @if (item.ModifiedDate == null)
                                    {
                                        <th></th>
                                    }
                                    else
                                    {
                                        <th>@item.ModifiedDate</th>
                                    }
                                    <th style="text-align:center;">
                                        <partial name="~/Views/Shared/_TableButtonPartial.cshtml" model="item.Id" />
                                    </th>

                                </tr>
                            }
                        </tbody>
                        @*<tfoot>
                                <tr>
                                    <th>Rendering engine</th>
                                    <th>Browser</th>
                                    <th>Platform(s)</th>
                                    <th>Engine version</th>
                                    <th>CSS grade</th>
                                </tr>
                            </tfoot>*@
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>

    </div>
</section>


@section Scripts{
    
    <script>
        $('#datepicker1').datepicker();
        $('#datepicker2').datepicker();        
        var selectedVal = "";


            $("#CategoryId").change(function () {
                debugger;
                // var selectedVal = $("#myselect option:selected").text();
                selectedVal = $("#CategoryId option:selected").val();
            });
            function Filter() {
                var categoryId = selectedVal;
                var fromTime = $('#datepicker1').val();
                var toTime = $('#datepicker2').val();
                //debugger;
                //var data = {
                //    categoryId: selectedVal,
                //    fromTime: $('#datepicker1').val(),
                //    toTime: $('#datepicker2').val()
                //}
                //$.ajax({
                //    url: "/Admin/MainService/Attributes",
                //    type: "get",
                //    data: data,
                //    dataType: "json",
                //    success: function (re) {

                //    },
                //    error: function (e) {
                //        console.log(e);
                //    }
                //});
                var url =""
                if (categoryId == "") {
                    if (fromTime == "" || toTime == "") {
                        alert("Vui lòng chọn mốc thơi gian");
                        return;
                    } else {
                        url = "/Admin/MainService/Attributes?categoryId=" + categoryId + "&fromTime=" + fromTime + "&toTime=" + toTime + "";

                    }
                } else {
                    url = "/Admin/MainService/Attributes?categoryId=" + categoryId + "&fromTime=" + fromTime + "&toTime=" + toTime + "";
                }
                window.location = url;
            }
    </script>
}

ComputerAccessories/Areas/Admin/Views/MainService/Brand.cshtml
@model List<ComputerAccessories.Models.TblBrand>
@{
    ViewData["Title"] = "Branch";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<link rel="stylesheet" href="~/font-awesome/font-awesome/css/font-awesome.css" />

<div class="page-header">
    <div class="row">
        <div class="col-lg-10">
            <h3>Danh mục brand</h3>
        </div>
        <div class="col-lg-1">
            <a class="btn btn-default" asp-area="Admin" asp-controller="MainService" asp-action="CreateNewBrand"><span><i class="fa fa-plus"></i></span> Thêm brand mới</a>
        </div>
    </div>
</div>
<br />

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Hover Data Table</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead style="color:darkcyan">
                        <tr>
                            <th>Mã</th>
                            <th>Tên brand</th>
                            <th>Logo</th>
                            <th>Ngày tạo </th>
                            <th>Ngày chỉnh sửa</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@item.Id</th>
                                <th>@item.BrandName</th>
                                <th>
                                    <img src="~/image/@item.Logo"/>
                                </th>
                                <th>@item.CreatedDate</th>
                                @if (item.ModifiedDate == null)
                                {
                                    <th></th>
                                }
                                else
                                {
                                    <th>@item.ModifiedDate</th>
                                }
                                <th style="text-align:center;">
                                    <partial name="~/Views/Shared/_TableButtonPartial.cshtml" model="item.Id" />
                                </th>

                            </tr>
                        }
                    </tbody>
                    @*<tfoot>
                            <tr>
                                <th>Rendering engine</th>
                                <th>Browser</th>
                                <th>Platform(s)</th>
                                <th>Engine version</th>
                                <th>CSS grade</th>
                            </tr>
                        </tfoot>*@
                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

</div>

ComputerAccessories/Areas/Admin/Views/MainService/Category.cshtml
@model List<ComputerAccessories.ViewModels.CategoryViewModel>
@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<link rel="stylesheet" href="~/font-awesome/font-awesome/css/font-awesome.css" />
    
    <div class="page-header">
        <div class="row">
            <div class="col-lg-10">
                <h3>Danh mục thương hiệu</h3>
            </div>
            <div class="col-lg-1">
                <a class="btn btn-default" asp-area="Admin" asp-controller="MainService" asp-action="CreateNewBranch" ><span><i class="fa fa-plus"></i></span> Thêm thương hiệu mới</a>
            </div>
        </div>
    </div>
    <br />

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Hover Data Table</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead style="color:darkcyan">
                            <tr>
                                <th>Mã</th>
                                <th>Tên danh mục</th>
                                <th>Danh mục cha</th>
                                <th>Ngày tạo </th>
                                <th>Ngày chỉnh sửa</th>
                                <th>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <th>@item.Id</th>
                                <th>@item.CategoryName</th>
                                @if (item.ParentName == null)
                                {
                                    <th>Trống</th>
                                }
                                else
                                {
                                    <th>@item.ParentName</th>

                                }
                                <th>@item.CreatedDate</th>
                                @if(item.ModifiedDate == null)
                                {
                                    <th></th>
                                }
                                else
                                {
                                    <th>@item.ModifiedDate</th>
                                }
                                <th style="text-align:center;">
                                    <partial name="~/Views/Shared/_TableButtonPartial.cshtml" model="item.Id" />
                                </th>

                            </tr>
                            }
                        </tbody>
                        @*<tfoot>
                            <tr>
                                <th>Rendering engine</th>
                                <th>Browser</th>
                                <th>Platform(s)</th>
                                <th>Engine version</th>
                                <th>CSS grade</th>
                            </tr>
                        </tfoot>*@
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>

    </div>

ComputerAccessories/Areas/Admin/Views/MainService/EditAttributes.cshtml
@model ComputerAccessories.ViewModels.AttributeViewModel
@using ComputerAccessories.Extensions
@{
    ViewData["Title"] = "CreateNewAttribute";
    Layout = "~/Views/Admin/_Layout.cshtml";
    List<TblCategory> categories = new List<TblCategory>();
    categories = ViewBag.lstCategory;
}

<br />



<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Chỉnh sửa thuộc tính</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" method="post" action="EditAttribute">
        <div class="box-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Tên danh mục</label>
                <input class="form-control" placeholder="Nhập tên danh mục" asp-for="AttributeName">
            </div>
        </div>
        <div class="box-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Danh mục</label>
                @*<input class="form-control" placeholder="Nhập tên danh mục" asp-for="CategoryName">*@
                @*<select class="form-control">
                        @foreach (var item in categories)
                        {
                            <option value="@item.Id">@item.CategoryName</option>
                        }
                    </select>*@

                <select asp-for="CategoryId" asp-items="@categories.ToSelectListItem("CategoryName",categories.FirstOrDefault().Id)" class="form-control"></select>
            </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Cập nhật</button>
            <a class="btn btn-warning" asp-action="Attributes" asp-controller="MainService">Quay lại</a>
        </div>
    </form>
</div>

@section Scripts{ 
<script>
    var value = "@Model.CategoryId";
    $("#CategoryId").val(value);
</script>
}

ComputerAccessories/Areas/Admin/Views/MainService/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_Layout.cshtml";
}

<h2>Index</h2>